# Generated by Django 4.1 on 2022-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Years', 'Years')], default='DY', max_length=255),
        ),
    ]
