# Generated by Django 4.1 on 2022-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membership_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
