# Generated by Django 4.1 on 2022-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='durction',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
