# Generated by Django 4.1 on 2022-09-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_durction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='durction',
            new_name='duration',
        ),
    ]
