# Generated by Django 4.1.1 on 2022-09-08 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
