# Generated by Django 4.1.1 on 2022-09-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseller',
            name='create_admin',
        ),
    ]
