# Generated by Django 4.1.1 on 2022-09-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='duration',
            new_name='expire_date',
        ),
    ]
