# Generated by Django 4.1.1 on 2022-09-08 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_reseller_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseller',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
