# Generated by Django 4.1.1 on 2022-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_remove_reseller_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='create_admin',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
