# Generated by Django 4.1.1 on 2022-09-08 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_reseller_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='reseller',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reseller',
        ),
        migrations.RemoveField(
            model_name='reseller',
            name='id',
        ),
        migrations.AlterField(
            model_name='reseller',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
