# Generated by Django 4.1.1 on 2022-09-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_reseller_create_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerOnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resellerstatus', to='Customer.reseller')),
            ],
        ),
    ]
