# Generated by Django 4.1.1 on 2022-09-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_credit_reseller_remove_customer_reseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='reseller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_reseller', to='Customer.reseller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='reseller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to='Customer.reseller'),
            preserve_default=False,
        ),
    ]
