# Generated by Django 4.1.1 on 2022-09-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_reselleronlinestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reselleronlinestatus',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='reselleronlinestatus',
            table='Reseller_Status',
        ),
    ]
