# Generated by Django 4.1.1 on 2022-09-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_reselleronlinestatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reselleronlinestatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='reselleronlinestatus',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resellerstatus', serialize=False, to='Customer.reseller'),
        ),
    ]
