# Generated by Django 4.1.1 on 2022-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_credit_reseller_customer_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='credit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reseller',
            name='isadmin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(choices=[('Trial', 'Trial'), ('Day', 'Day'), ('Month', 'Month'), ('Years', 'Years')], default='Trial', max_length=255),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Active', max_length=255),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
