# Generated by Django 4.1.1 on 2022-09-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_remove_reselleronlinestatus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reselleronlinestatus',
            name='reseller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resellerstatus', serialize=False, to='Customer.reseller'),
        ),
    ]
