name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: zainksa.xyz
        user: admin_vpn@zainksa.xyz
        password: 0K-b()cQIwQQ
        localDir: "dist"
        remoteDir: "www"
        options: "--delete --asci"
