name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: vpn.vipnet5g.host
        user: vpn_admin@vpn.vipnet5g.host
        password: YIC~mp9PA_1p
        localDir: "dist"
        remoteDir: "www"
        options: "--delete --asci"
